INSERT INTO user VALUES
(NULL,"Martin","Alexandre","0612345678","alexandre.martin@email.fr", NULL ,"employee",NULL),
(NULL,"Dubois","Sophie","0698765432","sophie.dubois@email.fr", NULL ,"employee",NULL),
(NULL,"Bernard","Julien","0622446688","julien.bernard@email.fr", NULL ,"employee",NULL),
(NULL,"Moreau","Camille","0611223344","camille.moreau@email.fr", NULL ,"employee",NULL),
(NULL,"Lefèvre","Lucie","0777889900","lucie.lefevre@email.fr", NULL ,"employee",NULL),
(NULL,"Leroy","Thomas","0655443322","thomas.leroy@email.fr", NULL ,"employee",NULL),
(NULL,"Roux","Chloé","0633221199","chloe.roux@email.fr", NULL ,"employee",NULL),
(NULL,"Petit","Maxime","0766778899","maxime.petit@email.fr", NULL ,"employee",NULL),
(NULL,"Garnier","Laura","0688776655","laura.garnier@email.fr", NULL ,"employee",NULL),
(NULL,"Dupuis","Antoine","0744556677","antoine.dupuis@email.fr", NULL ,"employee",NULL),
(NULL,"Lefebvre","Emma","0699887766","emma.lefebvre@email.fr", NULL ,"employee",NULL),
(NULL,"Fontaine","Louis","0655667788","louis.fontaine@email.fr", NULL ,"employee",NULL),
(NULL,"Chevalier","Clara","0788990011","clara.chevalier@email.fr", NULL ,"employee",NULL),
(NULL,"Robin","Nicolas","0644332211","nicolas.robin@email.fr", NULL ,"employee",NULL),
(NULL,"Gauthier","Marine","0677889922","marine.gauthier@email.fr", NULL ,"employee",NULL),
(NULL,"Fournier","Pierre","0722334455","pierre.fournier@email.fr", NULL ,"employee",NULL),
(NULL,"Girard","Sarah","0688665544","sarah.girard@email.fr", NULL ,"employee",NULL),
(NULL,"Lambert","Hugo","0611223366","hugo.lambert@email.fr", NULL ,"employee",NULL),
(NULL,"Masson","Julie","0733445566","julie.masson@email.fr", NULL ,"employee",NULL),
(NULL,"Henry","Arthur","0666554433","arthur.henry@email.fr", NULL ,"employee",NULL);

INSERT INTO agency VALUES
(NULL,"Paris"),
(NULL,"Lyon"),
(NULL,"Marseille"),
(NULL,"Toulouse"),
(NULL,"Nice"),
(NULL,"Nantes"),
(NULL,"Strasbourg"),
(NULL,"Montpellier"),
(NULL,"Bordeaux"),
(NULL,"Lille"),
(NULL,"Rennes"),
(NULL,"Reims");